---
title: "Untitled"
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(scales)
```


```{r}
data <- read.csv("candy_crush.csv")
head(data)
```


```{r}
data$dt <- as.Date(data$dt, format="%Y-%m-%d")
```


```{r}
# Count and display the number of unique players
print("Number of players:")
length(unique(data$player_id))

# Display the date range of the data
print("Period for which we have data:")
range(data$dt)
```

```{r}
# Calculating level difficulty
difficulty <- data %>%
  group_by(level) %>%
  summarise(attempts = sum(num_attempts), wins = sum(num_success)) %>%
  mutate(p_win = wins / attempts)

# Printing out the calculated difficulty
difficulty
```

```{r}
# Plotting the level difficulty profile
difficulty %>%
ggplot(aes(x=level, y = p_win)) +
geom_line() +
scale_x_continuous(breaks=1:15) +
scale_y_continuous(label = scales::percent)
```

```{r}
# Adding points and a dashed line
difficulty %>%
ggplot(aes(x=level, y = p_win)) +
geom_line() +geom_point() +
scale_x_continuous(breaks=1:15) +
scale_y_continuous(label = scales::percent)+
geom_hline(yintercept=0.05, linetype="dashed")
```

```{r}
# Computing the standard error of p_win for each level
difficulty <- difficulty %>%
group_by(level) %>%
mutate(error = sqrt(p_win * (1 - p_win) / attempts))

difficulty
```

```{r}
# Adding standard error bars
difficulty %>%
ggplot(aes(x=level, y = p_win)) +
geom_line() +geom_point() +
scale_x_continuous(breaks=1:15) +
scale_y_continuous(label = scales::percent)+
geom_hline(yintercept=0.1, linetype="dashed")+
geom_errorbar(aes(ymin=p_win - error, ymax=p_win + error))
```

```{r}
# The probability of completing the episode without losing a single time
p <- prod(difficulty$p_win) 

# Printing it out
p
```

```{r}
# Should our level designer worry about that a lot of 
# players will complete the episode in one attempt?
should_the_designer_worry = FALSE # TRUE / FALSE
should_the_designer_worry
```

